### ISSUE TITLE
cargo kcov does not properly upload to coveralls and codecov

### ISSUE THREAD

**Issue by Robbepop** [kennytm/cargo-kcov#21]
I switched from my old way to perform code coverage analysis to your neat cargo kcov utility for that purpose and while there seems to be no errors during a travisCI run there are no longer any proper uploads to coveralls or codecov for my [project](https://github.com/Robbepop/prophet/tree/next).

My old [`.travis.yml`](https://github.com/Robbepop/prophet/blob/master/.travis.yml) and my new (broken) [`.travis.yml`](https://github.com/Robbepop/prophet/blob/next/.travis.yml) can be found in those two links.

It seems that the coverage is computed and sent but when visiting coveralls and codecov it seems to arrive broken or empty or ... I don't actually know what exactly happens. :S

Here is the travis CI [output](https://travis-ci.org/Robbepop/prophet/jobs/290105751) of the latest run.

Links to my currently broken codecov and coveralls results:
- [codecov](https://codecov.io/gh/Robbepop/prophet/commit/07553979883742bb870c07dd9b67381f7da9d6ae)
- [coveralls](https://coveralls.io/builds/13797735)

Using cargo kcov locally works just fine and properly generates the correct coverage info in my `target/cov/` repo folder.

I really hope you can help me find the source of the error or tell me what I did wrong in using your cargo kcov in my `.travis.yml`.

**Comment by kennytm** [comment]
Hi.

I've reproduced the problem with the new `.travis.yml`, but I noted that your old `.travis.yml` was targeting the debug build, while the new one uses `--release`. There is no problem generating coverage when removing the `--release` flags.

kcov relies on debug symbols. Since release build by default won't generate debug symbols, the coverage will be empty. If you must use release build, try to [enable the debug symbols](http://doc.crates.io/manifest.html#the-profile-sections) with 

```toml
# in your Cargo.toml

[profile.bench]
debug = true
```

**Comment by Robbepop** [comment]
Thank you very much for your analysis. I never would have guessed that the problem is the `--release` ... Also thank you for providing a hint how to handle debug info with release configs.

My project does not require compiler optimizations, however, there seems to be no compilation overhead but the tests run a lot faster. (x5-10)
